# See: https://github.com/phusion/passenger-docker
# Latest image versions: https://github.com/phusion/passenger-docker/blob/master/Changelog.md
FROM phusion/passenger-ruby25:0.9.30

ENV HOME /root

# Use baseimage-docker's init process.
CMD ["/sbin/my_init"]

RUN apt-get update -qq && apt-get dist-upgrade --yes && \
  apt-get install --yes pkg-config apt-utils build-essential cmake automake\
  && apt-get upgrade --fix-missing --yes --allow-remove-essential \
  -o Dpkg::Options::="--force-confold"
  RUN apt-get install --yes tzdata udev locales curl git gnupg ca-certificates \
    gnupg libpq-dev nodejs wget \
    && apt-get clean && apt-get autoremove --yes && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | \
  apt-key add -

# Use en_CA.utf8 as our locale
RUN locale-gen en_CA.utf8
ENV LANG en_CA.utf8
ENV LANGUAGE en_CA:en
ENV LC_ALL en_CA.utf8

# Local machine uses 999 for docker user
RUN /usr/sbin/usermod -u 999 app

#ADD rails-env.conf /etc/nginx/main.d/rails-env.conf
#RUN chmod 644 /etc/nginx/main.d/rails-env.conf
ENV APP_HOME /home/app/workshops
ADD . $APP_HOME
WORKDIR $APP_HOME
RUN rm docker-compose.yml
RUN rm Dockerfile
RUN chown app -R ./

EXPOSE 80 443
ADD entrypoint.sh /sbin/
RUN rm entrypoint.sh
RUN chmod 755 /sbin/entrypoint.sh
RUN mkdir -p /etc/my_init.d
RUN ln -s /sbin/entrypoint.sh /etc/my_init.d/entrypoint.sh
ENTRYPOINT ["/sbin/entrypoint.sh"]
